name: buildx

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # See https://github.com/docker/setup-buildx-action
      # and https://github.com/docker/setup-qemu-action for details.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # Use "install" of true in order to avoid the warning message: The
        # requested image's platform (linux/arm/v7) does not match the detected
        # host platform (linux/amd64) and no specific platform was requested!
        with:
          install: true

      - name: Build
        run: |
          docker build .
